bing:
   api_key: AqNj2Azka9Dpb8astw8aJlB5yEu10JZ1Wy-Jpij0Q4Ciy0EjsE4NyPNmPbkXvAA4

google:
  browser_key: AIzaSyDbF0XQVbSm9l0iTEKKIOyAAx_nFiwZsLE
  server_key:  AIzaSyBCWnM0WAVcvM9s7MpeAP9utHZggFXfC9s
amazon:
  key: AKIAJCYFYW6H7JUJ342Q
  secret: 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